export const TYPE = {
  DISPUTE_CREATED: 0,
  APPEAL_POSSIBLE: 1,
  RULING_APPEALED: 2,
  TOKEN_SHIFT: 3,
  ARBITRATION_REWARD: 4,
  CAN_ACTIVATE: 5,
  CAN_REPARTITION: 6,
  CAN_EXECUTE: 7,
  CAN_PAY_FEE: 8
}
