export const LOCALHOST_ETH_PROVIDER = 'http://localhost:8545'
export const LOCALHOST_STORE_PROVIDER = 'https://kleros.in'
export const RNG_ADDRESS = ''
export const DISPUTE_STATUS = 3
export const DISPUTE_STATES = {
    OPEN: 0,
    RESOLVING: 1,
    EXECUTABLE: 2,
    RESOLVED: 3
}
export const PERIODS = {
  ACTIVATION: 0,
  DRAW: 1,
  VOTE: 2,
  APPEAL: 3,
  EXECUTE: 4
}
export const VOTING_PERIOD = 2
export const DISPUTE_STATE_INDEX = 6
export const NULL_ADDRESS = '0x'
export const DEFAULT_ARBITRATION_COST = 0.15
export const NOTIFICATION_TYPES = {
  DISPUTE_CREATED: 0,
  APPEAL_POSSIBLE: 1,
  RULING_APPEALED: 2,
  TOKEN_SHIFT: 3,
  ARBITRATION_REWARD: 4,
  CAN_ACTIVATE: 5,
  CAN_REPARTITION: 6,
  CAN_EXECUTE: 7,
  CAN_PAY_FEE: 8
}
export const CONTRACT_ARBITRABLE_STATUS = {
    NO_DISPUTE: 0,
    WAITING_PARTY_A: 1,
    WAITING_PARTY_A: 2,
    DISPUTE_CREATED: 3,
    RESOLVED: 4
}
