window.esdocSearchIndex = [
  [
    "kleros-api/src/contracts/abstractcontract.js~abstractcontract",
    "class/src/contracts/AbstractContract.js~AbstractContract.html",
    "<span>AbstractContract</span> <span class=\"search-result-import-path\">kleros-api/src/contracts/AbstractContract.js</span>",
    "class"
  ],
  [
    "kleros-api/src/contracts/implementations/arbitrable/arbitrable.js~arbitrable",
    "class/src/contracts/implementations/arbitrable/Arbitrable.js~Arbitrable.html",
    "<span>Arbitrable</span> <span class=\"search-result-import-path\">kleros-api/src/contracts/implementations/arbitrable/Arbitrable.js</span>",
    "class"
  ],
  [
    "kleros-api/src/contracts/abstractions/arbitrable.js~arbitrablecontract",
    "class/src/contracts/abstractions/Arbitrable.js~ArbitrableContract.html",
    "<span>ArbitrableContract</span> <span class=\"search-result-import-path\">kleros-api/src/contracts/abstractions/Arbitrable.js</span>",
    "class"
  ],
  [
    "kleros-api/src/contracts/abstractions/multiplearbitrable.js~arbitrablecontract",
    "class/src/contracts/abstractions/MultipleArbitrable.js~ArbitrableContract.html",
    "<span>ArbitrableContract</span> <span class=\"search-result-import-path\">kleros-api/src/contracts/abstractions/MultipleArbitrable.js</span>",
    "class"
  ],
  [
    "kleros-api/src/contracts/implementations/arbitrable/arbitrablepermissionlist.js~arbitrablepermissionlist",
    "class/src/contracts/implementations/arbitrable/ArbitrablePermissionList.js~ArbitrablePermissionList.html",
    "<span>ArbitrablePermissionList</span> <span class=\"search-result-import-path\">kleros-api/src/contracts/implementations/arbitrable/ArbitrablePermissionList.js</span>",
    "class"
  ],
  [
    "kleros-api/src/contracts/implementations/arbitrable/arbitrabletransaction.js~arbitrabletransaction",
    "class/src/contracts/implementations/arbitrable/ArbitrableTransaction.js~ArbitrableTransaction.html",
    "<span>ArbitrableTransaction</span> <span class=\"search-result-import-path\">kleros-api/src/contracts/implementations/arbitrable/ArbitrableTransaction.js</span>",
    "class"
  ],
  [
    "kleros-api/src/contracts/abstractions/arbitrator.js~arbitrator",
    "class/src/contracts/abstractions/Arbitrator.js~Arbitrator.html",
    "<span>Arbitrator</span> <span class=\"search-result-import-path\">kleros-api/src/contracts/abstractions/Arbitrator.js</span>",
    "class"
  ],
  [
    "kleros-api/src/resources/auth.js~auth",
    "class/src/resources/Auth.js~Auth.html",
    "<span>Auth</span> <span class=\"search-result-import-path\">kleros-api/src/resources/Auth.js</span>",
    "class"
  ],
  [
    "kleros-api/src/contracts/implementations/rng/blockhashrng.js~blockhashrng",
    "class/src/contracts/implementations/RNG/BlockHashRNG.js~BlockHashRNG.html",
    "<span>BlockHashRNG</span> <span class=\"search-result-import-path\">kleros-api/src/contracts/implementations/RNG/BlockHashRNG.js</span>",
    "class"
  ],
  [
    "kleros-api/src/contracts/contractimplementation.js~contractimplementation",
    "class/src/contracts/ContractImplementation.js~ContractImplementation.html",
    "<span>ContractImplementation</span> <span class=\"search-result-import-path\">kleros-api/src/contracts/ContractImplementation.js</span>",
    "class"
  ],
  [
    "kleros-api/src/resources/disputes.js~disputes",
    "class/src/resources/Disputes.js~Disputes.html",
    "<span>Disputes</span> <span class=\"search-result-import-path\">kleros-api/src/resources/Disputes.js</span>",
    "class"
  ],
  [
    "kleros-api/src/utils/eventlistener.js~eventlistener",
    "class/src/utils/EventListener.js~EventListener.html",
    "<span>EventListener</span> <span class=\"search-result-import-path\">kleros-api/src/utils/EventListener.js</span>",
    "class"
  ],
  [
    "kleros-api/src/contracts/implementations/arbitrator/kleros.js~kleros",
    "class/src/contracts/implementations/arbitrator/Kleros.js~Kleros.html",
    "<span>Kleros</span> <span class=\"search-result-import-path\">kleros-api/src/contracts/implementations/arbitrator/Kleros.js</span>",
    "class"
  ],
  [
    "kleros-api/src/kleros.js~kleros",
    "class/src/kleros.js~Kleros.html",
    "<span>Kleros</span> <span class=\"search-result-import-path\">kleros-api/src/kleros.js</span>",
    "class"
  ],
  [
    "kleros-api/src/contracts/implementations/arbitrator/klerospoc.js~klerospoc",
    "class/src/contracts/implementations/arbitrator/KlerosPOC.js~KlerosPOC.html",
    "<span>KlerosPOC</span> <span class=\"search-result-import-path\">kleros-api/src/contracts/implementations/arbitrator/KlerosPOC.js</span>",
    "class"
  ],
  [
    "kleros-api/src/contracts/implementations/pnk/minimepinakion.js~minimepinakion",
    "class/src/contracts/implementations/PNK/MiniMePinakion.js~MiniMePinakion.html",
    "<span>MiniMePinakion</span> <span class=\"search-result-import-path\">kleros-api/src/contracts/implementations/PNK/MiniMePinakion.js</span>",
    "class"
  ],
  [
    "kleros-api/src/contracts/implementations/arbitrable/multiplearbitrabletransaction.js~multiplearbitrabletransaction",
    "class/src/contracts/implementations/arbitrable/MultipleArbitrableTransaction.js~MultipleArbitrableTransaction.html",
    "<span>MultipleArbitrableTransaction</span> <span class=\"search-result-import-path\">kleros-api/src/contracts/implementations/arbitrable/MultipleArbitrableTransaction.js</span>",
    "class"
  ],
  [
    "kleros-api/src/resources/notifications.js~notifications",
    "class/src/resources/Notifications.js~Notifications.html",
    "<span>Notifications</span> <span class=\"search-result-import-path\">kleros-api/src/resources/Notifications.js</span>",
    "class"
  ],
  [
    "kleros-api/src/contracts/implementations/pnk/pinakionpoc.js~pinakionpoc",
    "class/src/contracts/implementations/PNK/PinakionPOC.js~PinakionPOC.html",
    "<span>PinakionPOC</span> <span class=\"search-result-import-path\">kleros-api/src/contracts/implementations/PNK/PinakionPOC.js</span>",
    "class"
  ],
  [
    "kleros-api/src/utils/promisequeue.js~promisequeue",
    "function/index.html#static-function-PromiseQueue",
    "<span>PromiseQueue</span> <span class=\"search-result-import-path\">kleros-api/src/utils/PromiseQueue.js</span>",
    "function"
  ],
  [
    "kleros-api/src/utils/storeproviderwrapper.js~storeproviderwrapper",
    "class/src/utils/StoreProviderWrapper.js~StoreProviderWrapper.html",
    "<span>StoreProviderWrapper</span> <span class=\"search-result-import-path\">kleros-api/src/utils/StoreProviderWrapper.js</span>",
    "class"
  ],
  [
    "kleros-api/src/contracts/implementations/pnk/tokenfactory.js~tokenfactory",
    "class/src/contracts/implementations/PNK/TokenFactory.js~TokenFactory.html",
    "<span>TokenFactory</span> <span class=\"search-result-import-path\">kleros-api/src/contracts/implementations/PNK/TokenFactory.js</span>",
    "class"
  ],
  [
    "kleros-api/src/utils/web3wrapper.js~web3wrapper",
    "class/src/utils/Web3Wrapper.js~Web3Wrapper.html",
    "<span>Web3Wrapper</span> <span class=\"search-result-import-path\">kleros-api/src/utils/Web3Wrapper.js</span>",
    "class"
  ],
  [
    "kleros-api/src/utils/delegatecalls.js~delegatecalls",
    "function/index.html#static-function-delegateCalls",
    "<span>delegateCalls</span> <span class=\"search-result-import-path\">kleros-api/src/utils/delegateCalls.js</span>",
    "function"
  ],
  [
    "kleros-api/src/utils/deploycontractasync.js~deploycontractasync",
    "function/index.html#static-function-deployContractAsync",
    "<span>deployContractAsync</span> <span class=\"search-result-import-path\">kleros-api/src/utils/deployContractAsync.js</span>",
    "function"
  ],
  [
    "kleros-api/src/utils/getcontractaddress.js~getcontractaddress",
    "function/index.html#static-function-getContractAddress",
    "<span>getContractAddress</span> <span class=\"search-result-import-path\">kleros-api/src/utils/getContractAddress.js</span>",
    "function"
  ],
  [
    "kleros-api/src/utils/httprequest.js~httprequest",
    "function/index.html#static-function-httpRequest",
    "<span>httpRequest</span> <span class=\"search-result-import-path\">kleros-api/src/utils/httpRequest.js</span>",
    "function"
  ],
  [
    "kleros-api/src/utils/isrequired.js~isrequired",
    "function/index.html#static-function-isRequired",
    "<span>isRequired</span> <span class=\"search-result-import-path\">kleros-api/src/utils/isRequired.js</span>",
    "function"
  ],
  [
    "src/.external-ecmascript.js~array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array",
    "src/.external-ecmascript.js~Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~arraybuffer",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer",
    "src/.external-ecmascript.js~ArrayBuffer",
    "external"
  ],
  [
    "src/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "src/.external-ecmascript.js~Boolean",
    "external"
  ],
  [
    "src/.external-ecmascript.js~dataview",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView",
    "src/.external-ecmascript.js~DataView",
    "external"
  ],
  [
    "src/.external-ecmascript.js~date",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date",
    "src/.external-ecmascript.js~Date",
    "external"
  ],
  [
    "src/.external-ecmascript.js~error",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error",
    "src/.external-ecmascript.js~Error",
    "external"
  ],
  [
    "src/.external-ecmascript.js~evalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/EvalError",
    "src/.external-ecmascript.js~EvalError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~float32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float32Array",
    "src/.external-ecmascript.js~Float32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~float64array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float64Array",
    "src/.external-ecmascript.js~Float64Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "src/.external-ecmascript.js~Function",
    "external"
  ],
  [
    "src/.external-ecmascript.js~generator",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Generator",
    "src/.external-ecmascript.js~Generator",
    "external"
  ],
  [
    "src/.external-ecmascript.js~generatorfunction",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/GeneratorFunction",
    "src/.external-ecmascript.js~GeneratorFunction",
    "external"
  ],
  [
    "src/.external-ecmascript.js~infinity",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Infinity",
    "src/.external-ecmascript.js~Infinity",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int16Array",
    "src/.external-ecmascript.js~Int16Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int32Array",
    "src/.external-ecmascript.js~Int32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int8Array",
    "src/.external-ecmascript.js~Int8Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~internalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/InternalError",
    "src/.external-ecmascript.js~InternalError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~json",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON",
    "src/.external-ecmascript.js~JSON",
    "external"
  ],
  [
    "src/.external-ecmascript.js~map",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map",
    "src/.external-ecmascript.js~Map",
    "external"
  ],
  [
    "src/.external-ecmascript.js~nan",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NaN",
    "src/.external-ecmascript.js~NaN",
    "external"
  ],
  [
    "src/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "src/.external-ecmascript.js~Number",
    "external"
  ],
  [
    "src/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "src/.external-ecmascript.js~Object",
    "external"
  ],
  [
    "src/.external-ecmascript.js~promise",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise",
    "src/.external-ecmascript.js~Promise",
    "external"
  ],
  [
    "src/.external-ecmascript.js~proxy",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy",
    "src/.external-ecmascript.js~Proxy",
    "external"
  ],
  [
    "src/.external-ecmascript.js~rangeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RangeError",
    "src/.external-ecmascript.js~RangeError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~referenceerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ReferenceError",
    "src/.external-ecmascript.js~ReferenceError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~reflect",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Reflect",
    "src/.external-ecmascript.js~Reflect",
    "external"
  ],
  [
    "src/.external-ecmascript.js~regexp",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp",
    "src/.external-ecmascript.js~RegExp",
    "external"
  ],
  [
    "src/.external-ecmascript.js~set",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set",
    "src/.external-ecmascript.js~Set",
    "external"
  ],
  [
    "src/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "src/.external-ecmascript.js~String",
    "external"
  ],
  [
    "src/.external-ecmascript.js~symbol",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol",
    "src/.external-ecmascript.js~Symbol",
    "external"
  ],
  [
    "src/.external-ecmascript.js~syntaxerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SyntaxError",
    "src/.external-ecmascript.js~SyntaxError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~typeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypeError",
    "src/.external-ecmascript.js~TypeError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~urierror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/URIError",
    "src/.external-ecmascript.js~URIError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint16Array",
    "src/.external-ecmascript.js~Uint16Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint32Array",
    "src/.external-ecmascript.js~Uint32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array",
    "src/.external-ecmascript.js~Uint8Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint8clampedarray",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8ClampedArray",
    "src/.external-ecmascript.js~Uint8ClampedArray",
    "external"
  ],
  [
    "src/.external-ecmascript.js~weakmap",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap",
    "src/.external-ecmascript.js~WeakMap",
    "external"
  ],
  [
    "src/.external-ecmascript.js~weakset",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakSet",
    "src/.external-ecmascript.js~WeakSet",
    "external"
  ],
  [
    "src/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "src/.external-ecmascript.js~boolean",
    "external"
  ],
  [
    "src/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "src/.external-ecmascript.js~function",
    "external"
  ],
  [
    "src/.external-ecmascript.js~null",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/null",
    "src/.external-ecmascript.js~null",
    "external"
  ],
  [
    "src/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "src/.external-ecmascript.js~number",
    "external"
  ],
  [
    "src/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "src/.external-ecmascript.js~object",
    "external"
  ],
  [
    "src/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "src/.external-ecmascript.js~string",
    "external"
  ],
  [
    "src/.external-ecmascript.js~undefined",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/undefined",
    "src/.external-ecmascript.js~undefined",
    "external"
  ],
  [
    "src/contracts/abstractcontract.js",
    "file/src/contracts/AbstractContract.js.html",
    "src/contracts/AbstractContract.js",
    "file"
  ],
  [
    "src/contracts/abstractcontract.js~abstractcontract#_storeprovider",
    "class/src/contracts/AbstractContract.js~AbstractContract.html#instance-member-_StoreProvider",
    "src/contracts/AbstractContract.js~AbstractContract#_StoreProvider",
    "member"
  ],
  [
    "src/contracts/abstractcontract.js~abstractcontract#_contractimplementation",
    "class/src/contracts/AbstractContract.js~AbstractContract.html#instance-member-_contractImplementation",
    "src/contracts/AbstractContract.js~AbstractContract#_contractImplementation",
    "member"
  ],
  [
    "src/contracts/abstractcontract.js~abstractcontract#constructor",
    "class/src/contracts/AbstractContract.js~AbstractContract.html#instance-constructor-constructor",
    "src/contracts/AbstractContract.js~AbstractContract#constructor",
    "method"
  ],
  [
    "src/contracts/abstractcontract.js~abstractcontract#setstoreproviderinstance",
    "class/src/contracts/AbstractContract.js~AbstractContract.html#instance-member-setStoreProviderInstance",
    "src/contracts/AbstractContract.js~AbstractContract#setStoreProviderInstance",
    "member"
  ],
  [
    "src/contracts/contractimplementation.js",
    "file/src/contracts/ContractImplementation.js.html",
    "src/contracts/ContractImplementation.js",
    "file"
  ],
  [
    "src/contracts/contractimplementation.js~contractimplementation#_web3wrapper",
    "class/src/contracts/ContractImplementation.js~ContractImplementation.html#instance-member-_Web3Wrapper",
    "src/contracts/ContractImplementation.js~ContractImplementation#_Web3Wrapper",
    "member"
  ],
  [
    "src/contracts/contractimplementation.js~contractimplementation#_contractloadedrejecter",
    "class/src/contracts/ContractImplementation.js~ContractImplementation.html#instance-member-_contractLoadedRejecter",
    "src/contracts/ContractImplementation.js~ContractImplementation#_contractLoadedRejecter",
    "member"
  ],
  [
    "src/contracts/contractimplementation.js~contractimplementation#_contractloadedresolver",
    "class/src/contracts/ContractImplementation.js~ContractImplementation.html#instance-member-_contractLoadedResolver",
    "src/contracts/ContractImplementation.js~ContractImplementation#_contractLoadedResolver",
    "member"
  ],
  [
    "src/contracts/contractimplementation.js~contractimplementation#_instantiatecontractifexistsasync",
    "class/src/contracts/ContractImplementation.js~ContractImplementation.html#instance-member-_instantiateContractIfExistsAsync",
    "src/contracts/ContractImplementation.js~ContractImplementation#_instantiateContractIfExistsAsync",
    "member"
  ],
  [
    "src/contracts/contractimplementation.js~contractimplementation#_load",
    "class/src/contracts/ContractImplementation.js~ContractImplementation.html#instance-member-_load",
    "src/contracts/ContractImplementation.js~ContractImplementation#_load",
    "member"
  ],
  [
    "src/contracts/contractimplementation.js~contractimplementation#_loadingcontractinstance",
    "class/src/contracts/ContractImplementation.js~ContractImplementation.html#instance-member-_loadingContractInstance",
    "src/contracts/ContractImplementation.js~ContractImplementation#_loadingContractInstance",
    "member"
  ],
  [
    "src/contracts/contractimplementation.js~contractimplementation#_newloadingpromise",
    "class/src/contracts/ContractImplementation.js~ContractImplementation.html#instance-member-_newLoadingPromise",
    "src/contracts/ContractImplementation.js~ContractImplementation#_newLoadingPromise",
    "member"
  ],
  [
    "src/contracts/contractimplementation.js~contractimplementation#artifact",
    "class/src/contracts/ContractImplementation.js~ContractImplementation.html#instance-member-artifact",
    "src/contracts/ContractImplementation.js~ContractImplementation#artifact",
    "member"
  ],
  [
    "src/contracts/contractimplementation.js~contractimplementation#constructor",
    "class/src/contracts/ContractImplementation.js~ContractImplementation.html#instance-constructor-constructor",
    "src/contracts/ContractImplementation.js~ContractImplementation#constructor",
    "method"
  ],
  [
    "src/contracts/contractimplementation.js~contractimplementation#contractaddress",
    "class/src/contracts/ContractImplementation.js~ContractImplementation.html#instance-member-contractAddress",
    "src/contracts/ContractImplementation.js~ContractImplementation#contractAddress",
    "member"
  ],
  [
    "src/contracts/contractimplementation.js~contractimplementation#contractinstance",
    "class/src/contracts/ContractImplementation.js~ContractImplementation.html#instance-member-contractInstance",
    "src/contracts/ContractImplementation.js~ContractImplementation#contractInstance",
    "member"
  ],
  [
    "src/contracts/contractimplementation.js~contractimplementation#getblock",
    "class/src/contracts/ContractImplementation.js~ContractImplementation.html#instance-member-getBlock",
    "src/contracts/ContractImplementation.js~ContractImplementation#getBlock",
    "member"
  ],
  [
    "src/contracts/contractimplementation.js~contractimplementation#getcontractaddress",
    "class/src/contracts/ContractImplementation.js~ContractImplementation.html#instance-member-getContractAddress",
    "src/contracts/ContractImplementation.js~ContractImplementation#getContractAddress",
    "member"
  ],
  [
    "src/contracts/contractimplementation.js~contractimplementation#getweb3provider",
    "class/src/contracts/ContractImplementation.js~ContractImplementation.html#instance-member-getWeb3Provider",
    "src/contracts/ContractImplementation.js~ContractImplementation#getWeb3Provider",
    "member"
  ],
  [
    "src/contracts/contractimplementation.js~contractimplementation#getweb3wrapper",
    "class/src/contracts/ContractImplementation.js~ContractImplementation.html#instance-member-getWeb3Wrapper",
    "src/contracts/ContractImplementation.js~ContractImplementation#getWeb3Wrapper",
    "member"
  ],
  [
    "src/contracts/contractimplementation.js~contractimplementation#isloading",
    "class/src/contracts/ContractImplementation.js~ContractImplementation.html#instance-member-isLoading",
    "src/contracts/ContractImplementation.js~ContractImplementation#isLoading",
    "member"
  ],
  [
    "src/contracts/contractimplementation.js~contractimplementation#loadcontract",
    "class/src/contracts/ContractImplementation.js~ContractImplementation.html#instance-member-loadContract",
    "src/contracts/ContractImplementation.js~ContractImplementation#loadContract",
    "member"
  ],
  [
    "src/contracts/contractimplementation.js~contractimplementation#setcontractinstance",
    "class/src/contracts/ContractImplementation.js~ContractImplementation.html#instance-member-setContractInstance",
    "src/contracts/ContractImplementation.js~ContractImplementation#setContractInstance",
    "member"
  ],
  [
    "src/contracts/abstractions/arbitrable.js",
    "file/src/contracts/abstractions/Arbitrable.js.html",
    "src/contracts/abstractions/Arbitrable.js",
    "file"
  ],
  [
    "src/contracts/abstractions/arbitrable.js~arbitrablecontract#deploy",
    "class/src/contracts/abstractions/Arbitrable.js~ArbitrableContract.html#instance-member-deploy",
    "src/contracts/abstractions/Arbitrable.js~ArbitrableContract#deploy",
    "member"
  ],
  [
    "src/contracts/abstractions/arbitrable.js~arbitrablecontract#getcontractsforuser",
    "class/src/contracts/abstractions/Arbitrable.js~ArbitrableContract.html#instance-member-getContractsForUser",
    "src/contracts/abstractions/Arbitrable.js~ArbitrableContract#getContractsForUser",
    "member"
  ],
  [
    "src/contracts/abstractions/arbitrable.js~arbitrablecontract#getdatafromstore",
    "class/src/contracts/abstractions/Arbitrable.js~ArbitrableContract.html#instance-member-getDataFromStore",
    "src/contracts/abstractions/Arbitrable.js~ArbitrableContract#getDataFromStore",
    "member"
  ],
  [
    "src/contracts/abstractions/arbitrable.js~arbitrablecontract#submitevidence",
    "class/src/contracts/abstractions/Arbitrable.js~ArbitrableContract.html#instance-member-submitEvidence",
    "src/contracts/abstractions/Arbitrable.js~ArbitrableContract#submitEvidence",
    "member"
  ],
  [
    "src/contracts/abstractions/arbitrator.js",
    "file/src/contracts/abstractions/Arbitrator.js.html",
    "src/contracts/abstractions/Arbitrator.js",
    "file"
  ],
  [
    "src/contracts/abstractions/arbitrator.js~arbitrator#buypnk",
    "class/src/contracts/abstractions/Arbitrator.js~Arbitrator.html#instance-member-buyPNK",
    "src/contracts/abstractions/Arbitrator.js~Arbitrator#buyPNK",
    "member"
  ],
  [
    "src/contracts/abstractions/arbitrator.js~arbitrator#getdisputesforuser",
    "class/src/contracts/abstractions/Arbitrator.js~Arbitrator.html#instance-member-getDisputesForUser",
    "src/contracts/abstractions/Arbitrator.js~Arbitrator#getDisputesForUser",
    "member"
  ],
  [
    "src/contracts/abstractions/arbitrator.js~arbitrator#getdisputesforuserfromstore",
    "class/src/contracts/abstractions/Arbitrator.js~Arbitrator.html#instance-member-getDisputesForUserFromStore",
    "src/contracts/abstractions/Arbitrator.js~Arbitrator#getDisputesForUserFromStore",
    "member"
  ],
  [
    "src/contracts/abstractions/multiplearbitrable.js",
    "file/src/contracts/abstractions/MultipleArbitrable.js.html",
    "src/contracts/abstractions/MultipleArbitrable.js",
    "file"
  ],
  [
    "src/contracts/abstractions/multiplearbitrable.js~arbitrablecontract#submitevidence",
    "class/src/contracts/abstractions/MultipleArbitrable.js~ArbitrableContract.html#instance-member-submitEvidence",
    "src/contracts/abstractions/MultipleArbitrable.js~ArbitrableContract#submitEvidence",
    "member"
  ],
  [
    "src/contracts/abstractions/index.js",
    "file/src/contracts/abstractions/index.js.html",
    "src/contracts/abstractions/index.js",
    "file"
  ],
  [
    "src/contracts/implementations/pnk/minimepinakion.js",
    "file/src/contracts/implementations/PNK/MiniMePinakion.js.html",
    "src/contracts/implementations/PNK/MiniMePinakion.js",
    "file"
  ],
  [
    "src/contracts/implementations/pnk/minimepinakion.js~minimepinakion#approveandcall",
    "class/src/contracts/implementations/PNK/MiniMePinakion.js~MiniMePinakion.html#instance-member-approveAndCall",
    "src/contracts/implementations/PNK/MiniMePinakion.js~MiniMePinakion#approveAndCall",
    "member"
  ],
  [
    "src/contracts/implementations/pnk/minimepinakion.js~minimepinakion#changecontroller",
    "class/src/contracts/implementations/PNK/MiniMePinakion.js~MiniMePinakion.html#instance-member-changeController",
    "src/contracts/implementations/PNK/MiniMePinakion.js~MiniMePinakion#changeController",
    "member"
  ],
  [
    "src/contracts/implementations/pnk/minimepinakion.js~minimepinakion#constructor",
    "class/src/contracts/implementations/PNK/MiniMePinakion.js~MiniMePinakion.html#instance-constructor-constructor",
    "src/contracts/implementations/PNK/MiniMePinakion.js~MiniMePinakion#constructor",
    "method"
  ],
  [
    "src/contracts/implementations/pnk/minimepinakion.js~minimepinakion#getcontroller",
    "class/src/contracts/implementations/PNK/MiniMePinakion.js~MiniMePinakion.html#instance-member-getController",
    "src/contracts/implementations/PNK/MiniMePinakion.js~MiniMePinakion#getController",
    "member"
  ],
  [
    "src/contracts/implementations/pnk/minimepinakion.js~minimepinakion#gettokenbalance",
    "class/src/contracts/implementations/PNK/MiniMePinakion.js~MiniMePinakion.html#instance-member-getTokenBalance",
    "src/contracts/implementations/PNK/MiniMePinakion.js~MiniMePinakion#getTokenBalance",
    "member"
  ],
  [
    "src/contracts/implementations/pnk/minimepinakion.js~minimepinakion.deploy",
    "class/src/contracts/implementations/PNK/MiniMePinakion.js~MiniMePinakion.html#static-member-deploy",
    "src/contracts/implementations/PNK/MiniMePinakion.js~MiniMePinakion.deploy",
    "member"
  ],
  [
    "src/contracts/implementations/pnk/pinakionpoc.js",
    "file/src/contracts/implementations/PNK/PinakionPOC.js.html",
    "src/contracts/implementations/PNK/PinakionPOC.js",
    "file"
  ],
  [
    "src/contracts/implementations/pnk/pinakionpoc.js~pinakionpoc#constructor",
    "class/src/contracts/implementations/PNK/PinakionPOC.js~PinakionPOC.html#instance-constructor-constructor",
    "src/contracts/implementations/PNK/PinakionPOC.js~PinakionPOC#constructor",
    "method"
  ],
  [
    "src/contracts/implementations/pnk/pinakionpoc.js~pinakionpoc#getdata",
    "class/src/contracts/implementations/PNK/PinakionPOC.js~PinakionPOC.html#instance-member-getData",
    "src/contracts/implementations/PNK/PinakionPOC.js~PinakionPOC#getData",
    "member"
  ],
  [
    "src/contracts/implementations/pnk/pinakionpoc.js~pinakionpoc#setkleros",
    "class/src/contracts/implementations/PNK/PinakionPOC.js~PinakionPOC.html#instance-member-setKleros",
    "src/contracts/implementations/PNK/PinakionPOC.js~PinakionPOC#setKleros",
    "member"
  ],
  [
    "src/contracts/implementations/pnk/pinakionpoc.js~pinakionpoc#transferownership",
    "class/src/contracts/implementations/PNK/PinakionPOC.js~PinakionPOC.html#instance-member-transferOwnership",
    "src/contracts/implementations/PNK/PinakionPOC.js~PinakionPOC#transferOwnership",
    "member"
  ],
  [
    "src/contracts/implementations/pnk/pinakionpoc.js~pinakionpoc.deploy",
    "class/src/contracts/implementations/PNK/PinakionPOC.js~PinakionPOC.html#static-member-deploy",
    "src/contracts/implementations/PNK/PinakionPOC.js~PinakionPOC.deploy",
    "member"
  ],
  [
    "src/contracts/implementations/pnk/tokenfactory.js",
    "file/src/contracts/implementations/PNK/TokenFactory.js.html",
    "src/contracts/implementations/PNK/TokenFactory.js",
    "file"
  ],
  [
    "src/contracts/implementations/pnk/tokenfactory.js~tokenfactory#constructor",
    "class/src/contracts/implementations/PNK/TokenFactory.js~TokenFactory.html#instance-constructor-constructor",
    "src/contracts/implementations/PNK/TokenFactory.js~TokenFactory#constructor",
    "method"
  ],
  [
    "src/contracts/implementations/pnk/tokenfactory.js~tokenfactory.deploy",
    "class/src/contracts/implementations/PNK/TokenFactory.js~TokenFactory.html#static-member-deploy",
    "src/contracts/implementations/PNK/TokenFactory.js~TokenFactory.deploy",
    "member"
  ],
  [
    "src/contracts/implementations/pnk/index.js",
    "file/src/contracts/implementations/PNK/index.js.html",
    "src/contracts/implementations/PNK/index.js",
    "file"
  ],
  [
    "src/contracts/implementations/rng/blockhashrng.js",
    "file/src/contracts/implementations/RNG/BlockHashRNG.js.html",
    "src/contracts/implementations/RNG/BlockHashRNG.js",
    "file"
  ],
  [
    "src/contracts/implementations/rng/blockhashrng.js~blockhashrng#constructor",
    "class/src/contracts/implementations/RNG/BlockHashRNG.js~BlockHashRNG.html#instance-constructor-constructor",
    "src/contracts/implementations/RNG/BlockHashRNG.js~BlockHashRNG#constructor",
    "method"
  ],
  [
    "src/contracts/implementations/rng/blockhashrng.js~blockhashrng.deploy",
    "class/src/contracts/implementations/RNG/BlockHashRNG.js~BlockHashRNG.html#static-member-deploy",
    "src/contracts/implementations/RNG/BlockHashRNG.js~BlockHashRNG.deploy",
    "member"
  ],
  [
    "src/contracts/implementations/rng/index.js",
    "file/src/contracts/implementations/RNG/index.js.html",
    "src/contracts/implementations/RNG/index.js",
    "file"
  ],
  [
    "src/contracts/implementations/arbitrable/arbitrable.js",
    "file/src/contracts/implementations/arbitrable/Arbitrable.js.html",
    "src/contracts/implementations/arbitrable/Arbitrable.js",
    "file"
  ],
  [
    "src/contracts/implementations/arbitrable/arbitrable.js~arbitrable#constructor",
    "class/src/contracts/implementations/arbitrable/Arbitrable.js~Arbitrable.html#instance-constructor-constructor",
    "src/contracts/implementations/arbitrable/Arbitrable.js~Arbitrable#constructor",
    "method"
  ],
  [
    "src/contracts/implementations/arbitrable/arbitrable.js~arbitrable#getcontractdata",
    "class/src/contracts/implementations/arbitrable/Arbitrable.js~Arbitrable.html#instance-member-getContractData",
    "src/contracts/implementations/arbitrable/Arbitrable.js~Arbitrable#getContractData",
    "member"
  ],
  [
    "src/contracts/implementations/arbitrable/arbitrable.js~arbitrable#getevidence",
    "class/src/contracts/implementations/arbitrable/Arbitrable.js~Arbitrable.html#instance-member-getEvidence",
    "src/contracts/implementations/arbitrable/Arbitrable.js~Arbitrable#getEvidence",
    "member"
  ],
  [
    "src/contracts/implementations/arbitrable/arbitrable.js~arbitrable#getmetaevidence",
    "class/src/contracts/implementations/arbitrable/Arbitrable.js~Arbitrable.html#instance-member-getMetaEvidence",
    "src/contracts/implementations/arbitrable/Arbitrable.js~Arbitrable#getMetaEvidence",
    "member"
  ],
  [
    "src/contracts/implementations/arbitrable/arbitrable.js~arbitrable#metaevidencecache",
    "class/src/contracts/implementations/arbitrable/Arbitrable.js~Arbitrable.html#instance-member-metaEvidenceCache",
    "src/contracts/implementations/arbitrable/Arbitrable.js~Arbitrable#metaEvidenceCache",
    "member"
  ],
  [
    "src/contracts/implementations/arbitrable/arbitrablepermissionlist.js",
    "file/src/contracts/implementations/arbitrable/ArbitrablePermissionList.js.html",
    "src/contracts/implementations/arbitrable/ArbitrablePermissionList.js",
    "file"
  ],
  [
    "src/contracts/implementations/arbitrable/arbitrablepermissionlist.js~arbitrablepermissionlist#constructor",
    "class/src/contracts/implementations/arbitrable/ArbitrablePermissionList.js~ArbitrablePermissionList.html#instance-constructor-constructor",
    "src/contracts/implementations/arbitrable/ArbitrablePermissionList.js~ArbitrablePermissionList#constructor",
    "method"
  ],
  [
    "src/contracts/implementations/arbitrable/arbitrablepermissionlist.js~arbitrablepermissionlist#getitembydisputeid",
    "class/src/contracts/implementations/arbitrable/ArbitrablePermissionList.js~ArbitrablePermissionList.html#instance-member-getItemByDisputeId",
    "src/contracts/implementations/arbitrable/ArbitrablePermissionList.js~ArbitrablePermissionList#getItemByDisputeId",
    "member"
  ],
  [
    "src/contracts/implementations/arbitrable/arbitrabletransaction.js",
    "file/src/contracts/implementations/arbitrable/ArbitrableTransaction.js.html",
    "src/contracts/implementations/arbitrable/ArbitrableTransaction.js",
    "file"
  ],
  [
    "src/contracts/implementations/arbitrable/arbitrabletransaction.js~arbitrabletransaction#appeal",
    "class/src/contracts/implementations/arbitrable/ArbitrableTransaction.js~ArbitrableTransaction.html#instance-member-appeal",
    "src/contracts/implementations/arbitrable/ArbitrableTransaction.js~ArbitrableTransaction#appeal",
    "member"
  ],
  [
    "src/contracts/implementations/arbitrable/arbitrabletransaction.js~arbitrabletransaction#calltimeoutpartya",
    "class/src/contracts/implementations/arbitrable/ArbitrableTransaction.js~ArbitrableTransaction.html#instance-member-callTimeOutPartyA",
    "src/contracts/implementations/arbitrable/ArbitrableTransaction.js~ArbitrableTransaction#callTimeOutPartyA",
    "member"
  ],
  [
    "src/contracts/implementations/arbitrable/arbitrabletransaction.js~arbitrabletransaction#calltimeoutpartyb",
    "class/src/contracts/implementations/arbitrable/ArbitrableTransaction.js~ArbitrableTransaction.html#instance-member-callTimeOutPartyB",
    "src/contracts/implementations/arbitrable/ArbitrableTransaction.js~ArbitrableTransaction#callTimeOutPartyB",
    "member"
  ],
  [
    "src/contracts/implementations/arbitrable/arbitrabletransaction.js~arbitrabletransaction#constructor",
    "class/src/contracts/implementations/arbitrable/ArbitrableTransaction.js~ArbitrableTransaction.html#instance-constructor-constructor",
    "src/contracts/implementations/arbitrable/ArbitrableTransaction.js~ArbitrableTransaction#constructor",
    "method"
  ],
  [
    "src/contracts/implementations/arbitrable/arbitrabletransaction.js~arbitrabletransaction#getdata",
    "class/src/contracts/implementations/arbitrable/ArbitrableTransaction.js~ArbitrableTransaction.html#instance-member-getData",
    "src/contracts/implementations/arbitrable/ArbitrableTransaction.js~ArbitrableTransaction#getData",
    "member"
  ],
  [
    "src/contracts/implementations/arbitrable/arbitrabletransaction.js~arbitrabletransaction#getparties",
    "class/src/contracts/implementations/arbitrable/ArbitrableTransaction.js~ArbitrableTransaction.html#instance-member-getParties",
    "src/contracts/implementations/arbitrable/ArbitrableTransaction.js~ArbitrableTransaction#getParties",
    "member"
  ],
  [
    "src/contracts/implementations/arbitrable/arbitrabletransaction.js~arbitrabletransaction#pay",
    "class/src/contracts/implementations/arbitrable/ArbitrableTransaction.js~ArbitrableTransaction.html#instance-member-pay",
    "src/contracts/implementations/arbitrable/ArbitrableTransaction.js~ArbitrableTransaction#pay",
    "member"
  ],
  [
    "src/contracts/implementations/arbitrable/arbitrabletransaction.js~arbitrabletransaction#payarbitrationfeebypartya",
    "class/src/contracts/implementations/arbitrable/ArbitrableTransaction.js~ArbitrableTransaction.html#instance-member-payArbitrationFeeByPartyA",
    "src/contracts/implementations/arbitrable/ArbitrableTransaction.js~ArbitrableTransaction#payArbitrationFeeByPartyA",
    "member"
  ],
  [
    "src/contracts/implementations/arbitrable/arbitrabletransaction.js~arbitrabletransaction#payarbitrationfeebypartyb",
    "class/src/contracts/implementations/arbitrable/ArbitrableTransaction.js~ArbitrableTransaction.html#instance-member-payArbitrationFeeByPartyB",
    "src/contracts/implementations/arbitrable/ArbitrableTransaction.js~ArbitrableTransaction#payArbitrationFeeByPartyB",
    "member"
  ],
  [
    "src/contracts/implementations/arbitrable/arbitrabletransaction.js~arbitrabletransaction#submitevidence",
    "class/src/contracts/implementations/arbitrable/ArbitrableTransaction.js~ArbitrableTransaction.html#instance-member-submitEvidence",
    "src/contracts/implementations/arbitrable/ArbitrableTransaction.js~ArbitrableTransaction#submitEvidence",
    "member"
  ],
  [
    "src/contracts/implementations/arbitrable/arbitrabletransaction.js~arbitrabletransaction.deploy",
    "class/src/contracts/implementations/arbitrable/ArbitrableTransaction.js~ArbitrableTransaction.html#static-member-deploy",
    "src/contracts/implementations/arbitrable/ArbitrableTransaction.js~ArbitrableTransaction.deploy",
    "member"
  ],
  [
    "src/contracts/implementations/arbitrable/multiplearbitrabletransaction.js",
    "file/src/contracts/implementations/arbitrable/MultipleArbitrableTransaction.js.html",
    "src/contracts/implementations/arbitrable/MultipleArbitrableTransaction.js",
    "file"
  ],
  [
    "src/contracts/implementations/arbitrable/multiplearbitrabletransaction.js~multiplearbitrabletransaction#appeal",
    "class/src/contracts/implementations/arbitrable/MultipleArbitrableTransaction.js~MultipleArbitrableTransaction.html#instance-member-appeal",
    "src/contracts/implementations/arbitrable/MultipleArbitrableTransaction.js~MultipleArbitrableTransaction#appeal",
    "member"
  ],
  [
    "src/contracts/implementations/arbitrable/multiplearbitrabletransaction.js~multiplearbitrabletransaction#arbitrabletransactionid",
    "class/src/contracts/implementations/arbitrable/MultipleArbitrableTransaction.js~MultipleArbitrableTransaction.html#instance-member-arbitrableTransactionId",
    "src/contracts/implementations/arbitrable/MultipleArbitrableTransaction.js~MultipleArbitrableTransaction#arbitrableTransactionId",
    "member"
  ],
  [
    "src/contracts/implementations/arbitrable/multiplearbitrabletransaction.js~multiplearbitrabletransaction#calltimeoutbuyer",
    "class/src/contracts/implementations/arbitrable/MultipleArbitrableTransaction.js~MultipleArbitrableTransaction.html#instance-member-callTimeOutBuyer",
    "src/contracts/implementations/arbitrable/MultipleArbitrableTransaction.js~MultipleArbitrableTransaction#callTimeOutBuyer",
    "member"
  ],
  [
    "src/contracts/implementations/arbitrable/multiplearbitrabletransaction.js~multiplearbitrabletransaction#calltimeoutseller",
    "class/src/contracts/implementations/arbitrable/MultipleArbitrableTransaction.js~MultipleArbitrableTransaction.html#instance-member-callTimeOutSeller",
    "src/contracts/implementations/arbitrable/MultipleArbitrableTransaction.js~MultipleArbitrableTransaction#callTimeOutSeller",
    "member"
  ],
  [
    "src/contracts/implementations/arbitrable/multiplearbitrabletransaction.js~multiplearbitrabletransaction#constructor",
    "class/src/contracts/implementations/arbitrable/MultipleArbitrableTransaction.js~MultipleArbitrableTransaction.html#instance-constructor-constructor",
    "src/contracts/implementations/arbitrable/MultipleArbitrableTransaction.js~MultipleArbitrableTransaction#constructor",
    "method"
  ],
  [
    "src/contracts/implementations/arbitrable/multiplearbitrabletransaction.js~multiplearbitrabletransaction#createarbitrabletransaction",
    "class/src/contracts/implementations/arbitrable/MultipleArbitrableTransaction.js~MultipleArbitrableTransaction.html#instance-member-createArbitrableTransaction",
    "src/contracts/implementations/arbitrable/MultipleArbitrableTransaction.js~MultipleArbitrableTransaction#createArbitrableTransaction",
    "member"
  ],
  [
    "src/contracts/implementations/arbitrable/multiplearbitrabletransaction.js~multiplearbitrabletransaction#getdata",
    "class/src/contracts/implementations/arbitrable/MultipleArbitrableTransaction.js~MultipleArbitrableTransaction.html#instance-member-getData",
    "src/contracts/implementations/arbitrable/MultipleArbitrableTransaction.js~MultipleArbitrableTransaction#getData",
    "member"
  ],
  [
    "src/contracts/implementations/arbitrable/multiplearbitrabletransaction.js~multiplearbitrabletransaction#pay",
    "class/src/contracts/implementations/arbitrable/MultipleArbitrableTransaction.js~MultipleArbitrableTransaction.html#instance-member-pay",
    "src/contracts/implementations/arbitrable/MultipleArbitrableTransaction.js~MultipleArbitrableTransaction#pay",
    "member"
  ],
  [
    "src/contracts/implementations/arbitrable/multiplearbitrabletransaction.js~multiplearbitrabletransaction#payarbitrationfeebybuyer",
    "class/src/contracts/implementations/arbitrable/MultipleArbitrableTransaction.js~MultipleArbitrableTransaction.html#instance-member-payArbitrationFeeByBuyer",
    "src/contracts/implementations/arbitrable/MultipleArbitrableTransaction.js~MultipleArbitrableTransaction#payArbitrationFeeByBuyer",
    "member"
  ],
  [
    "src/contracts/implementations/arbitrable/multiplearbitrabletransaction.js~multiplearbitrabletransaction#payarbitrationfeebyseller",
    "class/src/contracts/implementations/arbitrable/MultipleArbitrableTransaction.js~MultipleArbitrableTransaction.html#instance-member-payArbitrationFeeBySeller",
    "src/contracts/implementations/arbitrable/MultipleArbitrableTransaction.js~MultipleArbitrableTransaction#payArbitrationFeeBySeller",
    "member"
  ],
  [
    "src/contracts/implementations/arbitrable/multiplearbitrabletransaction.js~multiplearbitrabletransaction#reimburse",
    "class/src/contracts/implementations/arbitrable/MultipleArbitrableTransaction.js~MultipleArbitrableTransaction.html#instance-member-reimburse",
    "src/contracts/implementations/arbitrable/MultipleArbitrableTransaction.js~MultipleArbitrableTransaction#reimburse",
    "member"
  ],
  [
    "src/contracts/implementations/arbitrable/multiplearbitrabletransaction.js~multiplearbitrabletransaction#setarbitrabletransactionid",
    "class/src/contracts/implementations/arbitrable/MultipleArbitrableTransaction.js~MultipleArbitrableTransaction.html#instance-member-setArbitrableTransactionId",
    "src/contracts/implementations/arbitrable/MultipleArbitrableTransaction.js~MultipleArbitrableTransaction#setArbitrableTransactionId",
    "member"
  ],
  [
    "src/contracts/implementations/arbitrable/multiplearbitrabletransaction.js~multiplearbitrabletransaction#submitevidence",
    "class/src/contracts/implementations/arbitrable/MultipleArbitrableTransaction.js~MultipleArbitrableTransaction.html#instance-member-submitEvidence",
    "src/contracts/implementations/arbitrable/MultipleArbitrableTransaction.js~MultipleArbitrableTransaction#submitEvidence",
    "member"
  ],
  [
    "src/contracts/implementations/arbitrable/multiplearbitrabletransaction.js~multiplearbitrabletransaction.deploy",
    "class/src/contracts/implementations/arbitrable/MultipleArbitrableTransaction.js~MultipleArbitrableTransaction.html#static-member-deploy",
    "src/contracts/implementations/arbitrable/MultipleArbitrableTransaction.js~MultipleArbitrableTransaction.deploy",
    "member"
  ],
  [
    "src/contracts/implementations/arbitrable/index.js",
    "file/src/contracts/implementations/arbitrable/index.js.html",
    "src/contracts/implementations/arbitrable/index.js",
    "file"
  ],
  [
    "src/contracts/implementations/arbitrator/kleros.js",
    "file/src/contracts/implementations/arbitrator/Kleros.js.html",
    "src/contracts/implementations/arbitrator/Kleros.js",
    "file"
  ],
  [
    "src/contracts/implementations/arbitrator/kleros.js~kleros#_appealcreationtimestampcache",
    "class/src/contracts/implementations/arbitrator/Kleros.js~Kleros.html#instance-member-_appealCreationTimestampCache",
    "src/contracts/implementations/arbitrator/Kleros.js~Kleros#_appealCreationTimestampCache",
    "member"
  ],
  [
    "src/contracts/implementations/arbitrator/kleros.js~kleros#_appealruledattimestampcache",
    "class/src/contracts/implementations/arbitrator/Kleros.js~Kleros.html#instance-member-_appealRuledAtTimestampCache",
    "src/contracts/implementations/arbitrator/Kleros.js~Kleros#_appealRuledAtTimestampCache",
    "member"
  ],
  [
    "src/contracts/implementations/arbitrator/kleros.js~kleros#_disputedeadlinecache",
    "class/src/contracts/implementations/arbitrator/Kleros.js~Kleros.html#instance-member-_disputeDeadlineCache",
    "src/contracts/implementations/arbitrator/Kleros.js~Kleros#_disputeDeadlineCache",
    "member"
  ],
  [
    "src/contracts/implementations/arbitrator/kleros.js~kleros#_getnewperiodeventlogforsession",
    "class/src/contracts/implementations/arbitrator/Kleros.js~Kleros.html#instance-member-_getNewPeriodEventLogForSession",
    "src/contracts/implementations/arbitrator/Kleros.js~Kleros#_getNewPeriodEventLogForSession",
    "member"
  ],
  [
    "src/contracts/implementations/arbitrator/kleros.js~kleros#_gettimestampforblock",
    "class/src/contracts/implementations/arbitrator/Kleros.js~Kleros.html#instance-member-_getTimestampForBlock",
    "src/contracts/implementations/arbitrator/Kleros.js~Kleros#_getTimestampForBlock",
    "member"
  ],
  [
    "src/contracts/implementations/arbitrator/kleros.js~kleros#_opendisputescache",
    "class/src/contracts/implementations/arbitrator/Kleros.js~Kleros.html#instance-member-_openDisputesCache",
    "src/contracts/implementations/arbitrator/Kleros.js~Kleros#_openDisputesCache",
    "member"
  ],
  [
    "src/contracts/implementations/arbitrator/kleros.js~kleros#activatepnk",
    "class/src/contracts/implementations/arbitrator/Kleros.js~Kleros.html#instance-member-activatePNK",
    "src/contracts/implementations/arbitrator/Kleros.js~Kleros#activatePNK",
    "member"
  ],
  [
    "src/contracts/implementations/arbitrator/kleros.js~kleros#appealruling",
    "class/src/contracts/implementations/arbitrator/Kleros.js~Kleros.html#instance-member-appealRuling",
    "src/contracts/implementations/arbitrator/Kleros.js~Kleros#appealRuling",
    "member"
  ],
  [
    "src/contracts/implementations/arbitrator/kleros.js~kleros#canruledispute",
    "class/src/contracts/implementations/arbitrator/Kleros.js~Kleros.html#instance-member-canRuleDispute",
    "src/contracts/implementations/arbitrator/Kleros.js~Kleros#canRuleDispute",
    "member"
  ],
  [
    "src/contracts/implementations/arbitrator/kleros.js~kleros#constructor",
    "class/src/contracts/implementations/arbitrator/Kleros.js~Kleros.html#instance-constructor-constructor",
    "src/contracts/implementations/arbitrator/Kleros.js~Kleros#constructor",
    "method"
  ],
  [
    "src/contracts/implementations/arbitrator/kleros.js~kleros#currentrulingfordispute",
    "class/src/contracts/implementations/arbitrator/Kleros.js~Kleros.html#instance-member-currentRulingForDispute",
    "src/contracts/implementations/arbitrator/Kleros.js~Kleros#currentRulingForDispute",
    "member"
  ],
  [
    "src/contracts/implementations/arbitrator/kleros.js~kleros#executeruling",
    "class/src/contracts/implementations/arbitrator/Kleros.js~Kleros.html#instance-member-executeRuling",
    "src/contracts/implementations/arbitrator/Kleros.js~Kleros#executeRuling",
    "member"
  ],
  [
    "src/contracts/implementations/arbitrator/kleros.js~kleros#getamountofjurorsfordispute",
    "class/src/contracts/implementations/arbitrator/Kleros.js~Kleros.html#instance-member-getAmountOfJurorsForDispute",
    "src/contracts/implementations/arbitrator/Kleros.js~Kleros#getAmountOfJurorsForDispute",
    "member"
  ],
  [
    "src/contracts/implementations/arbitrator/kleros.js~kleros#getappealcost",
    "class/src/contracts/implementations/arbitrator/Kleros.js~Kleros.html#instance-member-getAppealCost",
    "src/contracts/implementations/arbitrator/Kleros.js~Kleros#getAppealCost",
    "member"
  ],
  [
    "src/contracts/implementations/arbitrator/kleros.js~kleros#getappealcreationtimestamp",
    "class/src/contracts/implementations/arbitrator/Kleros.js~Kleros.html#instance-member-getAppealCreationTimestamp",
    "src/contracts/implementations/arbitrator/Kleros.js~Kleros#getAppealCreationTimestamp",
    "member"
  ],
  [
    "src/contracts/implementations/arbitrator/kleros.js~kleros#getappealruledattimestamp",
    "class/src/contracts/implementations/arbitrator/Kleros.js~Kleros.html#instance-member-getAppealRuledAtTimestamp",
    "src/contracts/implementations/arbitrator/Kleros.js~Kleros#getAppealRuledAtTimestamp",
    "member"
  ],
  [
    "src/contracts/implementations/arbitrator/kleros.js~kleros#getarbitrationcost",
    "class/src/contracts/implementations/arbitrator/Kleros.js~Kleros.html#instance-member-getArbitrationCost",
    "src/contracts/implementations/arbitrator/Kleros.js~Kleros#getArbitrationCost",
    "member"
  ],
  [
    "src/contracts/implementations/arbitrator/kleros.js~kleros#getdata",
    "class/src/contracts/implementations/arbitrator/Kleros.js~Kleros.html#instance-member-getData",
    "src/contracts/implementations/arbitrator/Kleros.js~Kleros#getData",
    "member"
  ],
  [
    "src/contracts/implementations/arbitrator/kleros.js~kleros#getdispute",
    "class/src/contracts/implementations/arbitrator/Kleros.js~Kleros.html#instance-member-getDispute",
    "src/contracts/implementations/arbitrator/Kleros.js~Kleros#getDispute",
    "member"
  ],
  [
    "src/contracts/implementations/arbitrator/kleros.js~kleros#getdisputecreationevent",
    "class/src/contracts/implementations/arbitrator/Kleros.js~Kleros.html#instance-member-getDisputeCreationEvent",
    "src/contracts/implementations/arbitrator/Kleros.js~Kleros#getDisputeCreationEvent",
    "member"
  ],
  [
    "src/contracts/implementations/arbitrator/kleros.js~kleros#getdisputedeadlinetimestamp",
    "class/src/contracts/implementations/arbitrator/Kleros.js~Kleros.html#instance-member-getDisputeDeadlineTimestamp",
    "src/contracts/implementations/arbitrator/Kleros.js~Kleros#getDisputeDeadlineTimestamp",
    "member"
  ],
  [
    "src/contracts/implementations/arbitrator/kleros.js~kleros#getdisputesforjuror",
    "class/src/contracts/implementations/arbitrator/Kleros.js~Kleros.html#instance-member-getDisputesForJuror",
    "src/contracts/implementations/arbitrator/Kleros.js~Kleros#getDisputesForJuror",
    "member"
  ],
  [
    "src/contracts/implementations/arbitrator/kleros.js~kleros#getdrawsforjuror",
    "class/src/contracts/implementations/arbitrator/Kleros.js~Kleros.html#instance-member-getDrawsForJuror",
    "src/contracts/implementations/arbitrator/Kleros.js~Kleros#getDrawsForJuror",
    "member"
  ],
  [
    "src/contracts/implementations/arbitrator/kleros.js~kleros#getminactivatedtoken",
    "class/src/contracts/implementations/arbitrator/Kleros.js~Kleros.html#instance-member-getMinActivatedToken",
    "src/contracts/implementations/arbitrator/Kleros.js~Kleros#getMinActivatedToken",
    "member"
  ],
  [
    "src/contracts/implementations/arbitrator/kleros.js~kleros#getnettokensfordispute",
    "class/src/contracts/implementations/arbitrator/Kleros.js~Kleros.html#instance-member-getNetTokensForDispute",
    "src/contracts/implementations/arbitrator/Kleros.js~Kleros#getNetTokensForDispute",
    "member"
  ],
  [
    "src/contracts/implementations/arbitrator/kleros.js~kleros#getopendisputesforsession",
    "class/src/contracts/implementations/arbitrator/Kleros.js~Kleros.html#instance-member-getOpenDisputesForSession",
    "src/contracts/implementations/arbitrator/Kleros.js~Kleros#getOpenDisputesForSession",
    "member"
  ],
  [
    "src/contracts/implementations/arbitrator/kleros.js~kleros#getpnkbalance",
    "class/src/contracts/implementations/arbitrator/Kleros.js~Kleros.html#instance-member-getPNKBalance",
    "src/contracts/implementations/arbitrator/Kleros.js~Kleros#getPNKBalance",
    "member"
  ],
  [
    "src/contracts/implementations/arbitrator/kleros.js~kleros#getperiod",
    "class/src/contracts/implementations/arbitrator/Kleros.js~Kleros.html#instance-member-getPeriod",
    "src/contracts/implementations/arbitrator/Kleros.js~Kleros#getPeriod",
    "member"
  ],
  [
    "src/contracts/implementations/arbitrator/kleros.js~kleros#getsession",
    "class/src/contracts/implementations/arbitrator/Kleros.js~Kleros.html#instance-member-getSession",
    "src/contracts/implementations/arbitrator/Kleros.js~Kleros#getSession",
    "member"
  ],
  [
    "src/contracts/implementations/arbitrator/kleros.js~kleros#gettimeforperiod",
    "class/src/contracts/implementations/arbitrator/Kleros.js~Kleros.html#instance-member-getTimeForPeriod",
    "src/contracts/implementations/arbitrator/Kleros.js~Kleros#getTimeForPeriod",
    "member"
  ],
  [
    "src/contracts/implementations/arbitrator/kleros.js~kleros#getvotefordraw",
    "class/src/contracts/implementations/arbitrator/Kleros.js~Kleros.html#instance-member-getVoteForDraw",
    "src/contracts/implementations/arbitrator/Kleros.js~Kleros#getVoteForDraw",
    "member"
  ],
  [
    "src/contracts/implementations/arbitrator/kleros.js~kleros#getvoteforjuror",
    "class/src/contracts/implementations/arbitrator/Kleros.js~Kleros.html#instance-member-getVoteForJuror",
    "src/contracts/implementations/arbitrator/Kleros.js~Kleros#getVoteForJuror",
    "member"
  ],
  [
    "src/contracts/implementations/arbitrator/kleros.js~kleros#isjurordrawnfordispute",
    "class/src/contracts/implementations/arbitrator/Kleros.js~Kleros.html#instance-member-isJurorDrawnForDispute",
    "src/contracts/implementations/arbitrator/Kleros.js~Kleros#isJurorDrawnForDispute",
    "member"
  ],
  [
    "src/contracts/implementations/arbitrator/kleros.js~kleros#passperiod",
    "class/src/contracts/implementations/arbitrator/Kleros.js~Kleros.html#instance-member-passPeriod",
    "src/contracts/implementations/arbitrator/Kleros.js~Kleros#passPeriod",
    "member"
  ],
  [
    "src/contracts/implementations/arbitrator/kleros.js~kleros#repartitionjurortokens",
    "class/src/contracts/implementations/arbitrator/Kleros.js~Kleros.html#instance-member-repartitionJurorTokens",
    "src/contracts/implementations/arbitrator/Kleros.js~Kleros#repartitionJurorTokens",
    "member"
  ],
  [
    "src/contracts/implementations/arbitrator/kleros.js~kleros#submitvotes",
    "class/src/contracts/implementations/arbitrator/Kleros.js~Kleros.html#instance-member-submitVotes",
    "src/contracts/implementations/arbitrator/Kleros.js~Kleros#submitVotes",
    "member"
  ],
  [
    "src/contracts/implementations/arbitrator/kleros.js~kleros#transferpnktoarbitrator",
    "class/src/contracts/implementations/arbitrator/Kleros.js~Kleros.html#instance-member-transferPNKToArbitrator",
    "src/contracts/implementations/arbitrator/Kleros.js~Kleros#transferPNKToArbitrator",
    "member"
  ],
  [
    "src/contracts/implementations/arbitrator/kleros.js~kleros#withdrawpnk",
    "class/src/contracts/implementations/arbitrator/Kleros.js~Kleros.html#instance-member-withdrawPNK",
    "src/contracts/implementations/arbitrator/Kleros.js~Kleros#withdrawPNK",
    "member"
  ],
  [
    "src/contracts/implementations/arbitrator/kleros.js~kleros.deploy",
    "class/src/contracts/implementations/arbitrator/Kleros.js~Kleros.html#static-member-deploy",
    "src/contracts/implementations/arbitrator/Kleros.js~Kleros.deploy",
    "member"
  ],
  [
    "src/contracts/implementations/arbitrator/klerospoc.js",
    "file/src/contracts/implementations/arbitrator/KlerosPOC.js.html",
    "src/contracts/implementations/arbitrator/KlerosPOC.js",
    "file"
  ],
  [
    "src/contracts/implementations/arbitrator/klerospoc.js~klerospoc#buypnk",
    "class/src/contracts/implementations/arbitrator/KlerosPOC.js~KlerosPOC.html#instance-member-buyPNK",
    "src/contracts/implementations/arbitrator/KlerosPOC.js~KlerosPOC#buyPNK",
    "member"
  ],
  [
    "src/contracts/implementations/arbitrator/klerospoc.js~klerospoc#constructor",
    "class/src/contracts/implementations/arbitrator/KlerosPOC.js~KlerosPOC.html#instance-constructor-constructor",
    "src/contracts/implementations/arbitrator/KlerosPOC.js~KlerosPOC#constructor",
    "method"
  ],
  [
    "src/contracts/implementations/arbitrator/klerospoc.js~klerospoc.deploy",
    "class/src/contracts/implementations/arbitrator/KlerosPOC.js~KlerosPOC.html#static-member-deploy",
    "src/contracts/implementations/arbitrator/KlerosPOC.js~KlerosPOC.deploy",
    "member"
  ],
  [
    "src/contracts/implementations/arbitrator/index.js",
    "file/src/contracts/implementations/arbitrator/index.js.html",
    "src/contracts/implementations/arbitrator/index.js",
    "file"
  ],
  [
    "src/contracts/implementations/index.js",
    "file/src/contracts/implementations/index.js.html",
    "src/contracts/implementations/index.js",
    "file"
  ],
  [
    "src/contracts/index.js",
    "file/src/contracts/index.js.html",
    "src/contracts/index.js",
    "file"
  ],
  [
    "src/index.js",
    "file/src/index.js.html",
    "src/index.js",
    "file"
  ],
  [
    "src/kleros.js",
    "file/src/kleros.js.html",
    "src/kleros.js",
    "file"
  ],
  [
    "src/kleros.js~kleros#arbitrable",
    "class/src/kleros.js~Kleros.html#instance-member-arbitrable",
    "src/kleros.js~Kleros#arbitrable",
    "member"
  ],
  [
    "src/kleros.js~kleros#arbitrator",
    "class/src/kleros.js~Kleros.html#instance-member-arbitrator",
    "src/kleros.js~Kleros#arbitrator",
    "member"
  ],
  [
    "src/kleros.js~kleros#auth",
    "class/src/kleros.js~Kleros.html#instance-member-auth",
    "src/kleros.js~Kleros#auth",
    "member"
  ],
  [
    "src/kleros.js~kleros#constructor",
    "class/src/kleros.js~Kleros.html#instance-constructor-constructor",
    "src/kleros.js~Kleros#constructor",
    "method"
  ],
  [
    "src/kleros.js~kleros#disputes",
    "class/src/kleros.js~Kleros.html#instance-member-disputes",
    "src/kleros.js~Kleros#disputes",
    "member"
  ],
  [
    "src/kleros.js~kleros#eventlistener",
    "class/src/kleros.js~Kleros.html#instance-member-eventListener",
    "src/kleros.js~Kleros#eventListener",
    "member"
  ],
  [
    "src/kleros.js~kleros#notifications",
    "class/src/kleros.js~Kleros.html#instance-member-notifications",
    "src/kleros.js~Kleros#notifications",
    "member"
  ],
  [
    "src/kleros.js~kleros#setarbitrablecontractaddress",
    "class/src/kleros.js~Kleros.html#instance-member-setArbitrableContractAddress",
    "src/kleros.js~Kleros#setArbitrableContractAddress",
    "member"
  ],
  [
    "src/kleros.js~kleros#setstoreprovider",
    "class/src/kleros.js~Kleros.html#instance-member-setStoreProvider",
    "src/kleros.js~Kleros#setStoreProvider",
    "member"
  ],
  [
    "src/kleros.js~kleros#stopwatchingforevents",
    "class/src/kleros.js~Kleros.html#instance-member-stopWatchingForEvents",
    "src/kleros.js~Kleros#stopWatchingForEvents",
    "member"
  ],
  [
    "src/kleros.js~kleros#storewrapper",
    "class/src/kleros.js~Kleros.html#instance-member-storeWrapper",
    "src/kleros.js~Kleros#storeWrapper",
    "member"
  ],
  [
    "src/kleros.js~kleros#watchforevents",
    "class/src/kleros.js~Kleros.html#instance-member-watchForEvents",
    "src/kleros.js~Kleros#watchForEvents",
    "member"
  ],
  [
    "src/kleros.js~kleros#web3wrapper",
    "class/src/kleros.js~Kleros.html#instance-member-web3Wrapper",
    "src/kleros.js~Kleros#web3Wrapper",
    "member"
  ],
  [
    "src/resources/auth.js",
    "file/src/resources/Auth.js.html",
    "src/resources/Auth.js",
    "file"
  ],
  [
    "src/resources/auth.js~auth#_storeproviderinstance",
    "class/src/resources/Auth.js~Auth.html#instance-member-_StoreProviderInstance",
    "src/resources/Auth.js~Auth#_StoreProviderInstance",
    "member"
  ],
  [
    "src/resources/auth.js~auth#_web3wrapper",
    "class/src/resources/Auth.js~Auth.html#instance-member-_Web3Wrapper",
    "src/resources/Auth.js~Auth#_Web3Wrapper",
    "member"
  ],
  [
    "src/resources/auth.js~auth#constructor",
    "class/src/resources/Auth.js~Auth.html#instance-constructor-constructor",
    "src/resources/Auth.js~Auth#constructor",
    "method"
  ],
  [
    "src/resources/auth.js~auth#getnewauthtoken",
    "class/src/resources/Auth.js~Auth.html#instance-member-getNewAuthToken",
    "src/resources/Auth.js~Auth#getNewAuthToken",
    "member"
  ],
  [
    "src/resources/auth.js~auth#setauthtoken",
    "class/src/resources/Auth.js~Auth.html#instance-member-setAuthToken",
    "src/resources/Auth.js~Auth#setAuthToken",
    "member"
  ],
  [
    "src/resources/auth.js~auth#setstoreproviderinstance",
    "class/src/resources/Auth.js~Auth.html#instance-member-setStoreProviderInstance",
    "src/resources/Auth.js~Auth#setStoreProviderInstance",
    "member"
  ],
  [
    "src/resources/auth.js~auth#signmessage",
    "class/src/resources/Auth.js~Auth.html#instance-member-signMessage",
    "src/resources/Auth.js~Auth#signMessage",
    "member"
  ],
  [
    "src/resources/auth.js~auth#validateauthtoken",
    "class/src/resources/Auth.js~Auth.html#instance-member-validateAuthToken",
    "src/resources/Auth.js~Auth#validateAuthToken",
    "member"
  ],
  [
    "src/resources/disputes.js",
    "file/src/resources/Disputes.js.html",
    "src/resources/Disputes.js",
    "file"
  ],
  [
    "src/resources/disputes.js~disputes#_arbitrableinstance",
    "class/src/resources/Disputes.js~Disputes.html#instance-member-_ArbitrableInstance",
    "src/resources/Disputes.js~Disputes#_ArbitrableInstance",
    "member"
  ],
  [
    "src/resources/disputes.js~disputes#_arbitratorinstance",
    "class/src/resources/Disputes.js~Disputes.html#instance-member-_ArbitratorInstance",
    "src/resources/Disputes.js~Disputes#_ArbitratorInstance",
    "member"
  ],
  [
    "src/resources/disputes.js~disputes#_storeproviderinstance",
    "class/src/resources/Disputes.js~Disputes.html#instance-member-_StoreProviderInstance",
    "src/resources/Disputes.js~Disputes#_StoreProviderInstance",
    "member"
  ],
  [
    "src/resources/disputes.js~disputes#_getdisputestartblock",
    "class/src/resources/Disputes.js~Disputes.html#instance-member-_getDisputeStartBlock",
    "src/resources/Disputes.js~Disputes#_getDisputeStartBlock",
    "member"
  ],
  [
    "src/resources/disputes.js~disputes#_storenewdisputehandler",
    "class/src/resources/Disputes.js~Disputes.html#instance-member-_storeNewDisputeHandler",
    "src/resources/Disputes.js~Disputes#_storeNewDisputeHandler",
    "member"
  ],
  [
    "src/resources/disputes.js~disputes#_updatedisputecache",
    "class/src/resources/Disputes.js~Disputes.html#instance-member-_updateDisputeCache",
    "src/resources/Disputes.js~Disputes#_updateDisputeCache",
    "member"
  ],
  [
    "src/resources/disputes.js~disputes#constructor",
    "class/src/resources/Disputes.js~Disputes.html#instance-constructor-constructor",
    "src/resources/Disputes.js~Disputes#constructor",
    "method"
  ],
  [
    "src/resources/disputes.js~disputes#disputecache",
    "class/src/resources/Disputes.js~Disputes.html#instance-member-disputeCache",
    "src/resources/Disputes.js~Disputes#disputeCache",
    "member"
  ],
  [
    "src/resources/disputes.js~disputes#getappealcreatedat",
    "class/src/resources/Disputes.js~Disputes.html#instance-member-getAppealCreatedAt",
    "src/resources/Disputes.js~Disputes#getAppealCreatedAt",
    "member"
  ],
  [
    "src/resources/disputes.js~disputes#getappealruledat",
    "class/src/resources/Disputes.js~Disputes.html#instance-member-getAppealRuledAt",
    "src/resources/Disputes.js~Disputes#getAppealRuledAt",
    "member"
  ],
  [
    "src/resources/disputes.js~disputes#getdatafordispute",
    "class/src/resources/Disputes.js~Disputes.html#instance-member-getDataForDispute",
    "src/resources/Disputes.js~Disputes#getDataForDispute",
    "member"
  ],
  [
    "src/resources/disputes.js~disputes#getdisputedeadline",
    "class/src/resources/Disputes.js~Disputes.html#instance-member-getDisputeDeadline",
    "src/resources/Disputes.js~Disputes#getDisputeDeadline",
    "member"
  ],
  [
    "src/resources/disputes.js~disputes#getdisputefromstore",
    "class/src/resources/Disputes.js~Disputes.html#instance-member-getDisputeFromStore",
    "src/resources/Disputes.js~Disputes#getDisputeFromStore",
    "member"
  ],
  [
    "src/resources/disputes.js~disputes#registerstoreupdateeventlisteners",
    "class/src/resources/Disputes.js~Disputes.html#instance-member-registerStoreUpdateEventListeners",
    "src/resources/Disputes.js~Disputes#registerStoreUpdateEventListeners",
    "member"
  ],
  [
    "src/resources/disputes.js~disputes#setarbitrableinstance",
    "class/src/resources/Disputes.js~Disputes.html#instance-member-setArbitrableInstance",
    "src/resources/Disputes.js~Disputes#setArbitrableInstance",
    "member"
  ],
  [
    "src/resources/disputes.js~disputes#setarbitratorinstance",
    "class/src/resources/Disputes.js~Disputes.html#instance-member-setArbitratorInstance",
    "src/resources/Disputes.js~Disputes#setArbitratorInstance",
    "member"
  ],
  [
    "src/resources/disputes.js~disputes#setstoreproviderinstance",
    "class/src/resources/Disputes.js~Disputes.html#instance-member-setStoreProviderInstance",
    "src/resources/Disputes.js~Disputes#setStoreProviderInstance",
    "member"
  ],
  [
    "src/resources/notifications.js",
    "file/src/resources/Notifications.js.html",
    "src/resources/Notifications.js",
    "file"
  ],
  [
    "src/resources/notifications.js~notifications#_arbitrableinstance",
    "class/src/resources/Notifications.js~Notifications.html#instance-member-_ArbitrableInstance",
    "src/resources/Notifications.js~Notifications#_ArbitrableInstance",
    "member"
  ],
  [
    "src/resources/notifications.js~notifications#_arbitratorinstance",
    "class/src/resources/Notifications.js~Notifications.html#instance-member-_ArbitratorInstance",
    "src/resources/Notifications.js~Notifications#_ArbitratorInstance",
    "member"
  ],
  [
    "src/resources/notifications.js~notifications#_storeproviderinstance",
    "class/src/resources/Notifications.js~Notifications.html#instance-member-_StoreProviderInstance",
    "src/resources/Notifications.js~Notifications#_StoreProviderInstance",
    "member"
  ],
  [
    "src/resources/notifications.js~notifications#_web3wrapper",
    "class/src/resources/Notifications.js~Notifications.html#instance-member-_Web3Wrapper",
    "src/resources/Notifications.js~Notifications#_Web3Wrapper",
    "member"
  ],
  [
    "src/resources/notifications.js~notifications#_appealpossiblehandler",
    "class/src/resources/Notifications.js~Notifications.html#instance-member-_appealPossibleHandler",
    "src/resources/Notifications.js~Notifications#_appealPossibleHandler",
    "member"
  ],
  [
    "src/resources/notifications.js~notifications#_appealingdecisionhandler",
    "class/src/resources/Notifications.js~Notifications.html#instance-member-_appealingDecisionHandler",
    "src/resources/Notifications.js~Notifications#_appealingDecisionHandler",
    "member"
  ],
  [
    "src/resources/notifications.js~notifications#_arbitrationrewardhandler",
    "class/src/resources/Notifications.js~Notifications.html#instance-member-_arbitrationRewardHandler",
    "src/resources/Notifications.js~Notifications#_arbitrationRewardHandler",
    "member"
  ],
  [
    "src/resources/notifications.js~notifications#_createhandler",
    "class/src/resources/Notifications.js~Notifications.html#instance-member-_createHandler",
    "src/resources/Notifications.js~Notifications#_createHandler",
    "member"
  ],
  [
    "src/resources/notifications.js~notifications#_createnotification",
    "class/src/resources/Notifications.js~Notifications.html#instance-member-_createNotification",
    "src/resources/Notifications.js~Notifications#_createNotification",
    "member"
  ],
  [
    "src/resources/notifications.js~notifications#_disputecreationhandler",
    "class/src/resources/Notifications.js~Notifications.html#instance-member-_disputeCreationHandler",
    "src/resources/Notifications.js~Notifications#_disputeCreationHandler",
    "member"
  ],
  [
    "src/resources/notifications.js~notifications#_getcontracts",
    "class/src/resources/Notifications.js~Notifications.html#instance-member-_getContracts",
    "src/resources/Notifications.js~Notifications#_getContracts",
    "member"
  ],
  [
    "src/resources/notifications.js~notifications#_getdisputes",
    "class/src/resources/Notifications.js~Notifications.html#instance-member-_getDisputes",
    "src/resources/Notifications.js~Notifications#_getDisputes",
    "member"
  ],
  [
    "src/resources/notifications.js~notifications#_newnotification",
    "class/src/resources/Notifications.js~Notifications.html#instance-member-_newNotification",
    "src/resources/Notifications.js~Notifications#_newNotification",
    "member"
  ],
  [
    "src/resources/notifications.js~notifications#_newperiodhandler",
    "class/src/resources/Notifications.js~Notifications.html#instance-member-_newPeriodHandler",
    "src/resources/Notifications.js~Notifications#_newPeriodHandler",
    "member"
  ],
  [
    "src/resources/notifications.js~notifications#_requirestoreprovider",
    "class/src/resources/Notifications.js~Notifications.html#instance-member-_requireStoreProvider",
    "src/resources/Notifications.js~Notifications#_requireStoreProvider",
    "member"
  ],
  [
    "src/resources/notifications.js~notifications#_sendpushnotification",
    "class/src/resources/Notifications.js~Notifications.html#instance-member-_sendPushNotification",
    "src/resources/Notifications.js~Notifications#_sendPushNotification",
    "member"
  ],
  [
    "src/resources/notifications.js~notifications#_tokenshifthandler",
    "class/src/resources/Notifications.js~Notifications.html#instance-member-_tokenShiftHandler",
    "src/resources/Notifications.js~Notifications#_tokenShiftHandler",
    "member"
  ],
  [
    "src/resources/notifications.js~notifications#constructor",
    "class/src/resources/Notifications.js~Notifications.html#instance-constructor-constructor",
    "src/resources/Notifications.js~Notifications#constructor",
    "method"
  ],
  [
    "src/resources/notifications.js~notifications#getstatefulnotifications",
    "class/src/resources/Notifications.js~Notifications.html#instance-member-getStatefulNotifications",
    "src/resources/Notifications.js~Notifications#getStatefulNotifications",
    "member"
  ],
  [
    "src/resources/notifications.js~notifications#getstorednotifications",
    "class/src/resources/Notifications.js~Notifications.html#instance-member-getStoredNotifications",
    "src/resources/Notifications.js~Notifications#getStoredNotifications",
    "member"
  ],
  [
    "src/resources/notifications.js~notifications#getunreadstorednotifications",
    "class/src/resources/Notifications.js~Notifications.html#instance-member-getUnreadStoredNotifications",
    "src/resources/Notifications.js~Notifications#getUnreadStoredNotifications",
    "member"
  ],
  [
    "src/resources/notifications.js~notifications#markstorednotificationasread",
    "class/src/resources/Notifications.js~Notifications.html#instance-member-markStoredNotificationAsRead",
    "src/resources/Notifications.js~Notifications#markStoredNotificationAsRead",
    "member"
  ],
  [
    "src/resources/notifications.js~notifications#registerarbitratornotifications",
    "class/src/resources/Notifications.js~Notifications.html#instance-member-registerArbitratorNotifications",
    "src/resources/Notifications.js~Notifications#registerArbitratorNotifications",
    "member"
  ],
  [
    "src/resources/notifications.js~notifications#setarbitrableinstance",
    "class/src/resources/Notifications.js~Notifications.html#instance-member-setArbitrableInstance",
    "src/resources/Notifications.js~Notifications#setArbitrableInstance",
    "member"
  ],
  [
    "src/resources/notifications.js~notifications#setarbitratorinstance",
    "class/src/resources/Notifications.js~Notifications.html#instance-member-setArbitratorInstance",
    "src/resources/Notifications.js~Notifications#setArbitratorInstance",
    "member"
  ],
  [
    "src/resources/notifications.js~notifications#setstoreproviderinstance",
    "class/src/resources/Notifications.js~Notifications.html#instance-member-setStoreProviderInstance",
    "src/resources/Notifications.js~Notifications#setStoreProviderInstance",
    "member"
  ],
  [
    "src/resources/index.js",
    "file/src/resources/index.js.html",
    "src/resources/index.js",
    "file"
  ],
  [
    "src/utils/eventlistener.js",
    "file/src/utils/EventListener.js.html",
    "src/utils/EventListener.js",
    "file"
  ],
  [
    "src/utils/eventlistener.js~eventlistener#_queueevent",
    "class/src/utils/EventListener.js~EventListener.html#instance-member-_queueEvent",
    "src/utils/EventListener.js~EventListener#_queueEvent",
    "member"
  ],
  [
    "src/utils/eventlistener.js~eventlistener#addcontractimplementation",
    "class/src/utils/EventListener.js~EventListener.html#instance-member-addContractImplementation",
    "src/utils/EventListener.js~EventListener#addContractImplementation",
    "member"
  ],
  [
    "src/utils/eventlistener.js~eventlistener#addeventhandler",
    "class/src/utils/EventListener.js~EventListener.html#instance-member-addEventHandler",
    "src/utils/EventListener.js~EventListener#addEventHandler",
    "member"
  ],
  [
    "src/utils/eventlistener.js~eventlistener#constructor",
    "class/src/utils/EventListener.js~EventListener.html#instance-constructor-constructor",
    "src/utils/EventListener.js~EventListener#constructor",
    "method"
  ],
  [
    "src/utils/eventlistener.js~eventlistener#contracteventhandlermap",
    "class/src/utils/EventListener.js~EventListener.html#instance-member-contractEventHandlerMap",
    "src/utils/EventListener.js~EventListener#contractEventHandlerMap",
    "member"
  ],
  [
    "src/utils/eventlistener.js~eventlistener#contractinstances",
    "class/src/utils/EventListener.js~EventListener.html#instance-member-contractInstances",
    "src/utils/EventListener.js~EventListener#contractInstances",
    "member"
  ],
  [
    "src/utils/eventlistener.js~eventlistener#eventhandlerqueue",
    "class/src/utils/EventListener.js~EventListener.html#instance-member-eventHandlerQueue",
    "src/utils/EventListener.js~EventListener#eventHandlerQueue",
    "member"
  ],
  [
    "src/utils/eventlistener.js~eventlistener#removecontractinstance",
    "class/src/utils/EventListener.js~EventListener.html#instance-member-removeContractInstance",
    "src/utils/EventListener.js~EventListener#removeContractInstance",
    "member"
  ],
  [
    "src/utils/eventlistener.js~eventlistener#stopwatchingforevents",
    "class/src/utils/EventListener.js~EventListener.html#instance-member-stopWatchingForEvents",
    "src/utils/EventListener.js~EventListener#stopWatchingForEvents",
    "member"
  ],
  [
    "src/utils/eventlistener.js~eventlistener#watchforevents",
    "class/src/utils/EventListener.js~EventListener.html#instance-member-watchForEvents",
    "src/utils/EventListener.js~EventListener#watchForEvents",
    "member"
  ],
  [
    "src/utils/eventlistener.js~eventlistener#watcherinstances",
    "class/src/utils/EventListener.js~EventListener.html#instance-member-watcherInstances",
    "src/utils/EventListener.js~EventListener#watcherInstances",
    "member"
  ],
  [
    "src/utils/eventlistener.js~eventlistener.getalleventlogs",
    "class/src/utils/EventListener.js~EventListener.html#static-member-getAllEventLogs",
    "src/utils/EventListener.js~EventListener.getAllEventLogs",
    "member"
  ],
  [
    "src/utils/eventlistener.js~eventlistener.geteventlogs",
    "class/src/utils/EventListener.js~EventListener.html#static-member-getEventLogs",
    "src/utils/EventListener.js~EventListener.getEventLogs",
    "member"
  ],
  [
    "src/utils/promisequeue.js",
    "file/src/utils/PromiseQueue.js.html",
    "src/utils/PromiseQueue.js",
    "file"
  ],
  [
    "src/utils/storeproviderwrapper.js",
    "file/src/utils/StoreProviderWrapper.js.html",
    "src/utils/StoreProviderWrapper.js",
    "file"
  ],
  [
    "src/utils/storeproviderwrapper.js~storeproviderwrapper#_cachedprofiles",
    "class/src/utils/StoreProviderWrapper.js~StoreProviderWrapper.html#instance-member-_cachedProfiles",
    "src/utils/StoreProviderWrapper.js~StoreProviderWrapper#_cachedProfiles",
    "member"
  ],
  [
    "src/utils/storeproviderwrapper.js~storeproviderwrapper#_storequeue",
    "class/src/utils/StoreProviderWrapper.js~StoreProviderWrapper.html#instance-member-_storeQueue",
    "src/utils/StoreProviderWrapper.js~StoreProviderWrapper#_storeQueue",
    "member"
  ],
  [
    "src/utils/storeproviderwrapper.js~storeproviderwrapper#_storeuri",
    "class/src/utils/StoreProviderWrapper.js~StoreProviderWrapper.html#instance-member-_storeUri",
    "src/utils/StoreProviderWrapper.js~StoreProviderWrapper#_storeUri",
    "member"
  ],
  [
    "src/utils/storeproviderwrapper.js~storeproviderwrapper#addevidencecontract",
    "class/src/utils/StoreProviderWrapper.js~StoreProviderWrapper.html#instance-member-addEvidenceContract",
    "src/utils/StoreProviderWrapper.js~StoreProviderWrapper#addEvidenceContract",
    "member"
  ],
  [
    "src/utils/storeproviderwrapper.js~storeproviderwrapper#addnewdrawsdisputeprofile",
    "class/src/utils/StoreProviderWrapper.js~StoreProviderWrapper.html#instance-member-addNewDrawsDisputeProfile",
    "src/utils/StoreProviderWrapper.js~StoreProviderWrapper#addNewDrawsDisputeProfile",
    "member"
  ],
  [
    "src/utils/storeproviderwrapper.js~storeproviderwrapper#constructor",
    "class/src/utils/StoreProviderWrapper.js~StoreProviderWrapper.html#instance-constructor-constructor",
    "src/utils/StoreProviderWrapper.js~StoreProviderWrapper#constructor",
    "method"
  ],
  [
    "src/utils/storeproviderwrapper.js~storeproviderwrapper#getcontractbyaddress",
    "class/src/utils/StoreProviderWrapper.js~StoreProviderWrapper.html#instance-member-getContractByAddress",
    "src/utils/StoreProviderWrapper.js~StoreProviderWrapper#getContractByAddress",
    "member"
  ],
  [
    "src/utils/storeproviderwrapper.js~storeproviderwrapper#getdispute",
    "class/src/utils/StoreProviderWrapper.js~StoreProviderWrapper.html#instance-member-getDispute",
    "src/utils/StoreProviderWrapper.js~StoreProviderWrapper#getDispute",
    "member"
  ],
  [
    "src/utils/storeproviderwrapper.js~storeproviderwrapper#getdisputes",
    "class/src/utils/StoreProviderWrapper.js~StoreProviderWrapper.html#instance-member-getDisputes",
    "src/utils/StoreProviderWrapper.js~StoreProviderWrapper#getDisputes",
    "member"
  ],
  [
    "src/utils/storeproviderwrapper.js~storeproviderwrapper#getevidenceuri",
    "class/src/utils/StoreProviderWrapper.js~StoreProviderWrapper.html#instance-member-getEvidenceUri",
    "src/utils/StoreProviderWrapper.js~StoreProviderWrapper#getEvidenceUri",
    "member"
  ],
  [
    "src/utils/storeproviderwrapper.js~storeproviderwrapper#getlastblock",
    "class/src/utils/StoreProviderWrapper.js~StoreProviderWrapper.html#instance-member-getLastBlock",
    "src/utils/StoreProviderWrapper.js~StoreProviderWrapper#getLastBlock",
    "member"
  ],
  [
    "src/utils/storeproviderwrapper.js~storeproviderwrapper#getmetaevidenceuri",
    "class/src/utils/StoreProviderWrapper.js~StoreProviderWrapper.html#instance-member-getMetaEvidenceUri",
    "src/utils/StoreProviderWrapper.js~StoreProviderWrapper#getMetaEvidenceUri",
    "member"
  ],
  [
    "src/utils/storeproviderwrapper.js~storeproviderwrapper#getuserprofile",
    "class/src/utils/StoreProviderWrapper.js~StoreProviderWrapper.html#instance-member-getUserProfile",
    "src/utils/StoreProviderWrapper.js~StoreProviderWrapper#getUserProfile",
    "member"
  ],
  [
    "src/utils/storeproviderwrapper.js~storeproviderwrapper#marknotificationasread",
    "class/src/utils/StoreProviderWrapper.js~StoreProviderWrapper.html#instance-member-markNotificationAsRead",
    "src/utils/StoreProviderWrapper.js~StoreProviderWrapper#markNotificationAsRead",
    "member"
  ],
  [
    "src/utils/storeproviderwrapper.js~storeproviderwrapper#newnotification",
    "class/src/utils/StoreProviderWrapper.js~StoreProviderWrapper.html#instance-member-newNotification",
    "src/utils/StoreProviderWrapper.js~StoreProviderWrapper#newNotification",
    "member"
  ],
  [
    "src/utils/storeproviderwrapper.js~storeproviderwrapper#newuserprofile",
    "class/src/utils/StoreProviderWrapper.js~StoreProviderWrapper.html#instance-member-newUserProfile",
    "src/utils/StoreProviderWrapper.js~StoreProviderWrapper#newUserProfile",
    "member"
  ],
  [
    "src/utils/storeproviderwrapper.js~storeproviderwrapper#queuereadrequest",
    "class/src/utils/StoreProviderWrapper.js~StoreProviderWrapper.html#instance-member-queueReadRequest",
    "src/utils/StoreProviderWrapper.js~StoreProviderWrapper#queueReadRequest",
    "member"
  ],
  [
    "src/utils/storeproviderwrapper.js~storeproviderwrapper#queuewriterequest",
    "class/src/utils/StoreProviderWrapper.js~StoreProviderWrapper.html#instance-member-queueWriteRequest",
    "src/utils/StoreProviderWrapper.js~StoreProviderWrapper#queueWriteRequest",
    "member"
  ],
  [
    "src/utils/storeproviderwrapper.js~storeproviderwrapper#updatecontract",
    "class/src/utils/StoreProviderWrapper.js~StoreProviderWrapper.html#instance-member-updateContract",
    "src/utils/StoreProviderWrapper.js~StoreProviderWrapper#updateContract",
    "member"
  ],
  [
    "src/utils/storeproviderwrapper.js~storeproviderwrapper#updatedisputeprofile",
    "class/src/utils/StoreProviderWrapper.js~StoreProviderWrapper.html#instance-member-updateDisputeProfile",
    "src/utils/StoreProviderWrapper.js~StoreProviderWrapper#updateDisputeProfile",
    "member"
  ],
  [
    "src/utils/storeproviderwrapper.js~storeproviderwrapper#updatelastblock",
    "class/src/utils/StoreProviderWrapper.js~StoreProviderWrapper.html#instance-member-updateLastBlock",
    "src/utils/StoreProviderWrapper.js~StoreProviderWrapper#updateLastBlock",
    "member"
  ],
  [
    "src/utils/storeproviderwrapper.js~storeproviderwrapper#updateusersession",
    "class/src/utils/StoreProviderWrapper.js~StoreProviderWrapper.html#instance-member-updateUserSession",
    "src/utils/StoreProviderWrapper.js~StoreProviderWrapper#updateUserSession",
    "member"
  ],
  [
    "src/utils/web3wrapper.js",
    "file/src/utils/Web3Wrapper.js.html",
    "src/utils/Web3Wrapper.js",
    "file"
  ],
  [
    "src/utils/web3wrapper.js~web3wrapper#_getnetworkasync",
    "class/src/utils/Web3Wrapper.js~Web3Wrapper.html#instance-member-_getNetworkAsync",
    "src/utils/Web3Wrapper.js~Web3Wrapper#_getNetworkAsync",
    "member"
  ],
  [
    "src/utils/web3wrapper.js~web3wrapper#_getnetworkidifexistsasync",
    "class/src/utils/Web3Wrapper.js~Web3Wrapper.html#instance-member-_getNetworkIdIfExistsAsync",
    "src/utils/Web3Wrapper.js~Web3Wrapper#_getNetworkIdIfExistsAsync",
    "member"
  ],
  [
    "src/utils/web3wrapper.js~web3wrapper#_web3",
    "class/src/utils/Web3Wrapper.js~Web3Wrapper.html#instance-member-_web3",
    "src/utils/Web3Wrapper.js~Web3Wrapper#_web3",
    "member"
  ],
  [
    "src/utils/web3wrapper.js~web3wrapper#blocknumber",
    "class/src/utils/Web3Wrapper.js~Web3Wrapper.html#instance-member-blockNumber",
    "src/utils/Web3Wrapper.js~Web3Wrapper#blockNumber",
    "member"
  ],
  [
    "src/utils/web3wrapper.js~web3wrapper#constructor",
    "class/src/utils/Web3Wrapper.js~Web3Wrapper.html#instance-constructor-constructor",
    "src/utils/Web3Wrapper.js~Web3Wrapper#constructor",
    "method"
  ],
  [
    "src/utils/web3wrapper.js~web3wrapper#doescontractexistataddressasync",
    "class/src/utils/Web3Wrapper.js~Web3Wrapper.html#instance-member-doesContractExistAtAddressAsync",
    "src/utils/Web3Wrapper.js~Web3Wrapper#doesContractExistAtAddressAsync",
    "member"
  ],
  [
    "src/utils/web3wrapper.js~web3wrapper#fromwei",
    "class/src/utils/Web3Wrapper.js~Web3Wrapper.html#instance-member-fromWei",
    "src/utils/Web3Wrapper.js~Web3Wrapper#fromWei",
    "member"
  ],
  [
    "src/utils/web3wrapper.js~web3wrapper#getaccount",
    "class/src/utils/Web3Wrapper.js~Web3Wrapper.html#instance-member-getAccount",
    "src/utils/Web3Wrapper.js~Web3Wrapper#getAccount",
    "member"
  ],
  [
    "src/utils/web3wrapper.js~web3wrapper#getbalanceinweiasync",
    "class/src/utils/Web3Wrapper.js~Web3Wrapper.html#instance-member-getBalanceInWeiAsync",
    "src/utils/Web3Wrapper.js~Web3Wrapper#getBalanceInWeiAsync",
    "member"
  ],
  [
    "src/utils/web3wrapper.js~web3wrapper#getblock",
    "class/src/utils/Web3Wrapper.js~Web3Wrapper.html#instance-member-getBlock",
    "src/utils/Web3Wrapper.js~Web3Wrapper#getBlock",
    "member"
  ],
  [
    "src/utils/web3wrapper.js~web3wrapper#getcoinbase",
    "class/src/utils/Web3Wrapper.js~Web3Wrapper.html#instance-member-getCoinbase",
    "src/utils/Web3Wrapper.js~Web3Wrapper#getCoinbase",
    "member"
  ],
  [
    "src/utils/web3wrapper.js~web3wrapper#getnonce",
    "class/src/utils/Web3Wrapper.js~Web3Wrapper.html#instance-member-getNonce",
    "src/utils/Web3Wrapper.js~Web3Wrapper#getNonce",
    "member"
  ],
  [
    "src/utils/web3wrapper.js~web3wrapper#getprovider",
    "class/src/utils/Web3Wrapper.js~Web3Wrapper.html#instance-member-getProvider",
    "src/utils/Web3Wrapper.js~Web3Wrapper#getProvider",
    "member"
  ],
  [
    "src/utils/web3wrapper.js~web3wrapper#isaddress",
    "class/src/utils/Web3Wrapper.js~Web3Wrapper.html#instance-member-isAddress",
    "src/utils/Web3Wrapper.js~Web3Wrapper#isAddress",
    "member"
  ],
  [
    "src/utils/web3wrapper.js~web3wrapper#networkidifexists",
    "class/src/utils/Web3Wrapper.js~Web3Wrapper.html#instance-member-networkIdIfExists",
    "src/utils/Web3Wrapper.js~Web3Wrapper#networkIdIfExists",
    "member"
  ],
  [
    "src/utils/web3wrapper.js~web3wrapper#sign",
    "class/src/utils/Web3Wrapper.js~Web3Wrapper.html#instance-member-sign",
    "src/utils/Web3Wrapper.js~Web3Wrapper#sign",
    "member"
  ],
  [
    "src/utils/web3wrapper.js~web3wrapper#tobignumber",
    "class/src/utils/Web3Wrapper.js~Web3Wrapper.html#instance-member-toBigNumber",
    "src/utils/Web3Wrapper.js~Web3Wrapper#toBigNumber",
    "member"
  ],
  [
    "src/utils/web3wrapper.js~web3wrapper#towei",
    "class/src/utils/Web3Wrapper.js~Web3Wrapper.html#instance-member-toWei",
    "src/utils/Web3Wrapper.js~Web3Wrapper#toWei",
    "member"
  ],
  [
    "src/utils/delegatecalls.js",
    "file/src/utils/delegateCalls.js.html",
    "src/utils/delegateCalls.js",
    "file"
  ],
  [
    "src/utils/deploycontractasync.js",
    "file/src/utils/deployContractAsync.js.html",
    "src/utils/deployContractAsync.js",
    "file"
  ],
  [
    "src/utils/getcontractaddress.js",
    "file/src/utils/getContractAddress.js.html",
    "src/utils/getContractAddress.js",
    "file"
  ],
  [
    "src/utils/httprequest.js",
    "file/src/utils/httpRequest.js.html",
    "src/utils/httpRequest.js",
    "file"
  ],
  [
    "src/utils/isrequired.js",
    "file/src/utils/isRequired.js.html",
    "src/utils/isRequired.js",
    "file"
  ]
]